# Disable hardware Readback / Access Port protection for debugging
CONFIG_NRF_APPROTECT_DISABLE=y
CONFIG_NRF_SECURE_APPROTECT_DISABLE=y

#CONFIG_HEAP_MEM_POOL_SIZE=2048 # don't use malloc so don't care!
CONFIG_MAIN_STACK_SIZE=8192
# can test stack usage with
#CONFIG_THREAD_ANALYZER=y
#CONFIG_THREAD_ANALYZER_AUTO=y
#CONFIG_THREAD_ANALYZER_RUN_INTERVAL=5

CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_FLASH=y
CONFIG_FLASH_JESD216_API=y # ext flash

# Attempt to get XIP working -> failed
#CONFIG_SPI_NOR=y
#CONFIG_SPI_NOR_SFDP_RUNTIME=y
#CONFIG_XIP=y # doesn't seem to have enabled it?
#CONFIG_ARM_MPU=n # Disables the SPU's strict blocking for testing

# needed for uart_irq_callback_set
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_SERIAL=y
CONFIG_POSIX_API=y
CONFIG_POSIX_TIMERS=y # for RTC
CONFIG_MPU_ALLOW_FLASH_WRITE=y # flash write

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="NRF54L15"
CONFIG_BT_MAX_CONN=1
CONFIG_BT_MAX_PAIRED=1
CONFIG_BT_SMP=y
# Enable the NUS service
CONFIG_BT_NUS=y

# Enable bonding
#CONFIG_FLASH_PAGE_LAYOUT=y
#CONFIG_FLASH_MAP=y

# Config logger
CONFIG_LOG=y # needs chosen { zephyr,console = &uart0; zephyr,shell-uart = &uart0; } in dts if enabled
CONFIG_CONSOLE=y
#CONFIG_USE_SEGGER_RTT=y
#CONFIG_LOG_BACKEND_RTT=y
#CONFIG_LOG_BACKEND_UART=y
#CONFIG_LOG_PRINTK=n

CONFIG_ASSERT=y

# Disable UART Console
CONFIG_SERIAL=y

# Enable SEGGER RTT Console & Backend
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n

# Optional: Flush logs immediately during a panic/crash
CONFIG_LOG_MODE_IMMEDIATE=y